version: '3.3'
services:

    # The official MySQL (https://hub.docker.com/_/mysql/) supports only one 
    # MYSQL_DATABASE environment variable.
    # By modifying the entrypoint and passing shell script, you can create multiple 
    # dbs without having to make a mysql image just for this purpose.
    
    # Account Data Base
    account-db:
        image: mysql:5.7
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - ./account-service/db:/docker-entrypoint-initdb.d
        entrypoint:
            sh -c "/usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        ports:
            - 3306:3306

    # Order Data Base
    order-db:
        image: mysql:5.7
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - ./order-service/db:/docker-entrypoint-initdb.d
        entrypoint:
            sh -c "/usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        ports:
            - 3308:3306

    # Storage Data Base
    storage-db:
        image: mysql:5.7
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - ./storage-service/db:/docker-entrypoint-initdb.d
        entrypoint:
            sh -c "/usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        ports:
            - 3307:3306
