server:
    port: 8082
spring:
    application:
        name: order-service
    datasource:
        url: jdbc:mysql://account-service-db:3306/db_order?useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
    jpa:
        show-sql:true
    cloud:
        alibaba:
            seata:
                tx-service-group: fsp_tx_group
eureka:
    client:
        serviceUrl:
            defaultZone: http://discovery-server:8761/eureka/
feign:
    hystrix:
        enabled: false
logging:
    level:
        io:
            seata: debug
    org:
        springframework:
            cloud:
                alibaba:
                    seata:
                        web: debug
