 spring:
  application:
    name: account-service
 
---
spring:
  datasource:    
    url: jdbc:mysql://account-service-db:3306/db_account?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    show-sql: true   
    
---
server:
  port: 8083

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/