 spring:
  application:
    name: account-service
 
---
spring:
  datasource:    
    url: jdbc:mysql://account-service-db:3306/db_account?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    show-sql: true   
    
---
server:
  port: 8083

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

--- 
# https://github.com/seata/seata/blob/f1ee657f12607f38d95892a4b4e99364aab80963/script/client/spring/application.yml
seata:
    enabled: true
    application-id: account-service
    tx-service-group: seata_springcloud_jpa_group
    enable-auto-data-source-proxy: true
    use-jdk-proxy: false
    client:
        rm:
        async-commit-buffer-limit: 1000
        report-retry-count: 5
        table-meta-check-enable: false
        report-success-enable: true
        lock:
            retry-interval: 10
            retry-times: 30
            retry-policy-branch-rollback-on-conflict: true
        tm:
            commit-retry-count: 5
            rollback-retry-count: 5
        undo:
            data-validation: true
            log-serialization: jackson
            log-table: undo_log
        log:
            exceptionRate: 100
    service:
        #transaction service group mapping
        vgroup-mapping: default
        grouplist: "seata-server:8091"        
        enable-degrade: false     
        #disable seata
        disable-global-transaction: false           
    transport:
        shutdown:
            wait: 3
        thread-factory:
            boss-thread-prefix: NettyBoss
            worker-thread-prefix: NettyServerNIOWorker
            server-executor-thread-prefix: NettyServerBizHandler
            share-boss-worker: false
            client-selector-thread-prefix: NettyClientSelector
            client-selector-thread-size: 1
            client-worker-thread-prefix: NettyClientWorkerThread
        type: TCP
        server: NIO
        heartbeat: true
        serialization: seata
        compressor: none
        enable-client-batch-send-request: true
    eureka:
        application: default
        weight: 1
        service-url: http://discovery-server:8761/eureka
    config:
        type: file
        file:
            name: file.conf
        consul:
            server-addr: 127.0.0.1:8500
        apollo:
            apollo-meta: http://192.168.1.204:8801
            app-id: seata-server
            namespace: application
        etcd3:
            server-addr: http://localhost:2379
        nacos:
            namespace:
            serverAddr: localhost
            group: SEATA_GROUP
        zk:
            server-addr: 127.0.0.1:2181
            session-timeout: 6000
            connect-timeout: 2000
    registry:
        type: file
        file:
            name: file.conf
        consul:
            cluster: default
            server-addr: 127.0.0.1:8500
        etcd3:
            cluster: default
            serverAddr: http://localhost:2379
        eureka:
            application: default
            weight: 1
            service-url: http://discovery-server:8761/eureka
        nacos:
            cluster: default
            server-addr: localhost
            namespace:
        redis:
            server-addr: localhost:6379
            db: 0
            password:
            cluster: default
            timeout: 0
        sofa:
            server-addr: 127.0.0.1:9603
            application: default
            region: DEFAULT_ZONE
            datacenter: DefaultDataCenter
            cluster: default
            group: SEATA_GROUP
            addressWaitTime: 3000
        zk:
            cluster: default
            server-addr: 127.0.0.1:2181
            session-timeout: 6000
            connect-timeout: 2000    