 spring:
  application:
    name: storage-service
 
---
spring:
  datasource:    
    url: jdbc:mysql://storage-service-db:3306/db_storage?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    show-sql: true   
    
---
server:
  port: 8081
  
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/